FROM php:7.3-apache
RUN docker-php-ext-install mysqli pdo_mysql
RUN apt-get update \
    && apt-get install -y libzip-dev \
    && apt-get install -y zlib1g-dev \
    && rm -rf /var/lib/apt/lists/* \
    && docker-php-ext-install zip
RUN chmod -R 777 /var/www/html
RUN cp config.TEMPLATE.inc.php config.inc.php
